quiz_db = {
    # Python
    "Python": {
        "What keyword is used to create a function in Python?": "def",
        "Which data type is immutable: list or tuple?": "tuple",
        "What does the 'len()' function do?": "Returns the length of an object",
        "What symbol is used for list comprehension in Python?": "[]",
        "How do you handle exceptions in Python?": "Using try and except blocks",

        # SOLID Principles
        "What does the 'S' in SOLID stand for?": "Single Responsibility Principle",
        "What is the Open/Closed Principle?": "Software should be open for extension but closed for modification",
        "What does the Liskov Substitution Principle ensure?": "Subtypes must be substitutable for their base types",
        "What is the Interface Segregation Principle?": "Clients should not be forced to depend on interfaces they do not use",
        "What is the Dependency Inversion Principle?": "High-level modules should not depend on low-level modules, but on abstractions",

        # OOP Concepts
        "What is encapsulation in OOP?": "The bundling of data and methods that operate on that data within a class",
        "What is inheritance in OOP?": "A mechanism where a class can inherit properties and behavior from another class",
        "What is polymorphism in OOP?": "The ability to take many forms, allowing objects to be treated as instances of their parent class",
        "What is abstraction in OOP?": "Hiding complex implementation details and showing only the necessary features",
        "What is a class in Python?": "A blueprint for creating objects",

        # Scope and Variables
        "What is a local variable?": "A variable declared inside a function and accessible only within it",
        "What is a global variable in Python?": "A variable declared outside all functions and accessible globally",
        "How do you declare a global variable inside a function?": "Using the 'global' keyword",
        "What is the LEGB rule in Python?": "It defines the order of variable scope lookup: Local, Enclosing, Global, Built-in",

        # Type Conversion
        "How do you convert a string to an integer in Python?": "Using the int() function",
        "How do you convert an integer to a float?": "Using the float() function",
        "How do you convert a list to a set?": "Using the set() function",
        "How do you convert a list to a tuple?": "Using the tuple() function",

        # Matrix
        "What is a matrix in programming?": "A 2D array or list of lists representing rows and columns",
        "How do you access an element in a matrix at row 2, column 3?": "Using matrix[1][2] in Python (0-based indexing)",

        # Methods and Built-in Functions
        "What does the .append() method do in a list?": "Adds an element to the end of a list",
        "What does the .pop() method do in a list?": "Removes and returns the last element of the list",
        "What does the .update() method do in a dictionary?": "Updates the dictionary with elements from another dictionary or iterable",
        "What does the .get() method do in a dictionary?": "Returns the value for a specified key if the key exists, otherwise returns None",
        "What does the .keys() method return in a dictionary?": "A view object that displays a list of all the keys",
        "What does the .values() method return in a dictionary?": "A view object that displays a list of all the values",
        "What does the .items() method return in a dictionary?": "A view object that displays a list of key-value tuple pairs",
        "How do you remove a key from a dictionary?": "Using the del statement or the pop() method",
        "What is the difference between del and pop in a dictionary?": "del removes a key without returning it; pop removes and returns the value",

        # Notations and Syntax
        "What is the symbol for exponentiation in Python?": "**",
        "What is the output of 10 // 3?": "3 (Floor division)",
        "What does 'is' compare in Python?": "Object identity (memory location)",
        "What does '==' compare in Python?": "Object value (equality)",
        "What is a docstring?": "A string used to document a function or module, enclosed in triple quotes",
        "What is the purpose of the pass statement?": "A placeholder that does nothing, used in blocks that are syntactically required",

        # Miscellaneous
        "How do you iterate over a list in Python?": "Using a for loop",
        "What does the range() function do?": "Generates a sequence of numbers",
        "What does enumerate() return?": "Index-value pairs from an iterable",
        "What is a lambda function?": "An anonymous function defined with the lambda keyword",
        "How do you import a specific function from a module?": "Using 'from module import function_name'",
        "What is list slicing?": "Extracting parts of a list using the syntax list[start:end:step]",
        "What is a dictionary comprehension?": "A compact way to construct a dictionary using {key: value for ...}",
        "What is the default return value of a function with no return statement?": "None",
        "What built-in function is used to get user input?": "input()"
    },

    # Logics
    "Logics": {
        # Logical Operators & Basics
        "What is the result of False or True?": "True",
        "What is the result of not (True and False)?": "True",
        "What is the result of True or False and False?": "True",
        "What is the identity element for the logical AND operator?": "True",
        "What is the identity element for the logical OR operator?": "False",

        # Truth Tables & Boolean Logic
        "If p is True and q is True, what is p and q?": "True",
        "If p is False and q is True, what is p or q?": "True",
        "If p is False, what is not p?": "True",
        "What is the result of (p or q) if p is False and q is False?": "False",
        "If p is True and q is False, what is p → q?": "False",

        # Logical Equivalences
        "What is the equivalent of not (p and q)?": "not p or not q",
        "What is the equivalent of not (p or q)?": "not p and not q",
        "What is the equivalent of p → q?": "not p or q",
        "What is the equivalent of p ↔ q?": "(p → q) and (q → p)",
        "What is the double negation of p?": "p",

        # Tautology / Contradiction / Contingency
        "What kind of formula is always false regardless of inputs?": "Contradiction",
        "What kind of formula is true in some cases and false in others?": "Contingency",
        "What is a contradiction?": "A formula that is always false",
        "Which expression is the following: p or not p?": "Tautology",
        "Which expression is the following: p and not p?": "Contradiction",

        # Natural Language Logic Translation
        "Translate: 'If it rains, then the ground is wet'": "rains → wet",
        "Translate: 'Either she studies or she fails'": "studies or fails",
        "Translate: 'You can’t enter if you’re not a member'": "not member → not enter",
        "Translate: 'If the light is on, then the switch is up'": "light_on → switch_up",
        "Translate: 'I will go out only if it is sunny'": "go_out → sunny",

        # Symbol Matching
        "What does the symbol '∧' represent in logic?": "and",
        "What does the symbol '∨' represent in logic?": "or",
        "What does '¬' mean in logic?": "not",
        "What does '→' mean in propositional logic?": "implies",
        "What does '↔' mean in logic?": "if and only if",

        # Logic Puzzles
        "If a statement is true and its negation is also true, what is the logical conclusion?": "Contradiction",
        "If p → q is true and p is true, what must q be?": "True",
        "If not p is False, what is p?": "True",
        "If p and q are both False, what is p ↔ q?": "True",
        "If p is True and q is True, what is not (p → q)?": "False",

        # Evaluation / Equivalence
        "What does 'p or (p and q)' simplify to?": "p",
        "What does '(p and q) or (p and not q)' simplify to?": "p",
        "What does 'not (not p)' simplify to?": "p",
        "What does '(p and q) → p' evaluate to?": "True",
        "What does 'p → (p or q)' evaluate to?": "True",

        # Logic Word Problems
        "If it is not true that both Alice and Bob passed, what is the expression?": "not (Alice and Bob)",
        "If either the dog barks or the cat meows, and the cat does not meow, what happens?": "The dog barks",
        "If it is not sunny and not warm, what is the expression?": "not sunny and not warm",
        "If the store is open only if the lights are on, and the lights are off, is the store open?": "No",
        "If both switches must be on for the circuit to work, how is this expressed?": "switch1 and switch2",

        # Deductive Reasoning
        "If p → q and q → r, what can be inferred?": "p → r",
        "If not (p and q) is true, what can you infer?": "At least one of p or q is false",
        "If p is true and p ↔ q is true, what is q?": "True",
        "If (p or q) and not p is true, what is q?": "True",
        "If p is false and p or q is true, what must q be?": "True",

        # Logical Fallacies / Misunderstandings
        "Is 'p → q' the same as 'q → p'?": "No",
        "Can both a statement and its negation be true?": "No",
        "If p → q is false, which values must p and q have?": "p is True, q is False",
        "What is a common mistake with assuming p → q means q → p?": "Affirming the consequent",
        "If q is true and p → q is true, can we conclude p is true?": "No"
    },

    #Mathematics
    "Mathematics": {
        "What is the binary representation of the decimal number 10?": "1010",
        "What is 2^5?": "32",
        "What is the result of 7 % 3?": "1",
        "What is the time complexity of binary search?": "O(log n)",
        "What is the least common multiple of 4 and 6?": "12",

        # Binary, Hex, Octal, Base Conversion
        "What is the binary representation of decimal 255?": "11111111",
        "What is the hexadecimal value of decimal 15?": "F",
        "What is the decimal representation of binary 1001?": "9",
        "What is 0b1010 + 0b0011 in binary?": "1101",
        "What is the octal value of decimal 64?": "100",

        # Arithmetic & Order of Operations
        "What is 3 * (2 + 5)?": "21",
        "What is the result of 10 - 2 * 3?": "4",
        "What is the value of 2 ** 3 ** 2?": "512",
        "What is 100 divided by 4.0?": "25.0",
        "What is the integer division of 29 // 5?": "5",

        # Modulo & Remainders
        "What is 10 % 4?": "2",
        "What is the result of -7 % 3 in Python?": "2",
        "What does n % 2 == 0 check for?": "Even numbers",
        "What is the remainder when 13 is divided by 5?": "3",
        "What is 15 % 15?": "0",

        # Factors, GCD, LCM
        "What is the greatest common divisor of 8 and 12?": "4",
        "What is the least common multiple of 3 and 5?": "15",
        "What are the factors of 12?": "1, 2, 3, 4, 6, 12",
        "What is the result of 60 divided by its GCD with 48?": "5",
        "What is the smallest prime number?": "2",

        # Prime & Composite
        "Is 17 a prime number?": "Yes",
        "Is 1 a prime number?": "No",
        "Which prime number comes after 7?": "11",
        "What is the sum of the first 3 prime numbers?": "10",
        "How many divisors does 28 have?": "6",

        # Bitwise Logic
        "What is 5 & 3 in binary?": "1",
        "What is 5 | 2 in binary?": "7",
        "What is 5 ^ 1 in binary?": "4",
        "What does 1 << 3 evaluate to?": "8",
        "What does 8 >> 2 evaluate to?": "2",

        # Algorithmic Complexity
        "What is the time complexity of linear search?": "O(n)",
        "What is the time complexity of bubble sort (worst-case)?": "O(n^2)",
        "What is the time complexity of merge sort?": "O(n log n)",
        "What is the time complexity of inserting into a Python list at the end?": "O(1)",
        "What is the time complexity of accessing an element in a list by index?": "O(1)",

        # Probability & Combinatorics
        "How many permutations of 3 items are there?": "6",
        "How many combinations of 2 items from 4 exist?": "6",
        "What is the factorial of 5?": "120",
        "What is 0! (zero factorial)?": "1",
        "How many binary strings of length 4 are there?": "16",

        # Numeric Ranges
        "What is the range of values for an 8-bit unsigned integer?": "0 to 255",
        "How many bits are in a byte?": "8",
        "What is the max value of a signed 16-bit integer?": "32767",
        "What is the min value of a signed 16-bit integer?": "-32768",
        "What is the range of a signed 32-bit integer?": "-2147483648 to 2147483647"
    },

    # PostgreSql
    "PostgreSQL": {
            "Which command is used to retrieve data from a table?": "SELECT",
        "What keyword is used to prevent duplicate results?": "DISTINCT",
        "What is a foreign key used for?": "To reference a primary key in another table",
        "Which data type is used to store large text in PostgreSQL?": "TEXT",

        # Syntax & Commands
        "Which keyword is used to insert new rows into a table?": "INSERT",
        "What keyword is used to update existing records?": "UPDATE",
        "What keyword is used to delete rows from a table?": "DELETE",
        "What clause is used to filter rows based on a condition?": "WHERE",
        "Which clause is used to sort results?": "ORDER BY",
        "What clause groups rows sharing a property?": "GROUP BY",
        "What clause filters grouped rows?": "HAVING",
        "What keyword is used to create a new table?": "CREATE",
        "What keyword removes an entire table?": "DROP",
        "Which clause limits the number of rows returned?": "LIMIT",
        "What keyword is used to rename a table or column?": "RENAME",
        "What keyword is used to change a table structure?": "ALTER",

        # Theory & Structure
        "What is the purpose of a primary key?": "To uniquely identify each row",
        "Can a primary key contain NULL values?": "No",
        "Can a table have multiple foreign keys?": "Yes",
        "What is a composite key?": "A key made of two or more columns",
        "What is normalization?": "Organizing data to reduce redundancy",
        "Which normal form eliminates repeating groups?": "First Normal Form",
        "Which form removes partial dependencies?": "Second Normal Form",
        "What is a view?": "A virtual table based on a query",
        "What is an index used for?": "To speed up data retrieval",
        "What happens when you don’t use an index?": "Slower query performance",
        "What is a schema in PostgreSQL?": "A logical container for database objects",
        "What does ACID stand for?": "Atomicity, Consistency, Isolation, Durability",
        "What is a transaction?": "A unit of work that is either fully completed or rolled back",

        # Best & Bad Practices
        "Is using SELECT * in production considered good practice?": "No",
        "Why is using SELECT * discouraged?": "It fetches unnecessary data",
        "Should passwords be stored in plain text in a database?": "No",
        "Why should you parameterize SQL queries?": "To prevent SQL injection",
        "Should you always use indexes on every column?": "No",
        "Why can too many indexes be a bad thing?": "They slow down writes and consume space",
        "Is it a good idea to mix transactional and analytical data in one table?": "No",
        "Why should column names be lowercase with underscores?": "For consistency and readability",
        "Why is NULL handling important in SQL queries?": "Because NULL affects comparison and aggregation",

        # Data Types
        "Which type stores whole numbers?": "INTEGER",
        "Which type stores true/false values?": "BOOLEAN",
        "What type stores date and time values?": "TIMESTAMP",
        "What type stores currency values?": "NUMERIC or MONEY",
        "Which type is used for UUIDs?": "UUID",

        # SQL vs NoSQL
        "Is PostgreSQL a relational database?": "Yes",
        "Is MongoDB a relational database?": "No",
        "Which is better for highly relational data?": "SQL",
        "Which is better for hierarchical or flexible schemas?": "NoSQL",
        "Can PostgreSQL store JSON data?": "Yes",
        "What does NoSQL stand for?": "Not Only SQL",
        "Is schema enforcement strict in SQL databases?": "Yes",
        "Which type of database uses collections and documents?": "NoSQL",
        "Are JOINs native in NoSQL databases?": "No",
        "Which is generally easier to scale horizontally?": "NoSQL",

        # Use Cases
        "Which type of database is best for banking systems?": "SQL",
        "Which is more suitable for logging user events?": "NoSQL",
        "Which is better for complex queries across multiple relations?": "SQL",
        "What kind of application benefits most from ACID compliance?": "Financial applications",
        "Which is ideal for quick prototyping with flexible schemas?": "NoSQL"
    },

    # HTML 5
    "HTML5": {
        "What HTML5 element is used to define navigation links?": "<nav>",
        "Which element is used for embedding a video?": "<video>",
        "What does the <input> element do?": "Creates an interactive control in a web form",
        "What attribute is used to link a CSS file?": "rel='stylesheet'",
        "What tag is used to create a table row?": "<tr>",
        "Which tag defines the main content of a document?": "<main>",
        "Which tag is used to insert a line break?": "<br>",
        "What tag is used for emphasized text?": "<em>",
        "Which tag represents a short quotation?": "<q>",
        "What tag defines a cell in a table?": "<td>",
        "Which tag is used to create a numbered list?": "<ol>",
        "Which tag is used to create an unordered list?": "<ul>",
        "Which tag is used to define list items?": "<li>",
        "What tag is used to define a hyperlink?": "<a>",
        "Which tag defines an image?": "<img>",
        "Which tag is used for bold text without extra importance?": "<b>",
        "Which tag is used for bold text with importance?": "<strong>",
        "What does the <section> tag define?": "A section in a document",
        "What does the <article> tag define?": "Independent, self-contained content",
        "What tag is used to define a footer for a document or section?": "<footer>",
        "Which tag defines a header for a document or section?": "<header>",
        "What tag is used to mark up contact information?": "<address>",
        "Which tag represents a thematic break in content?": "<hr>",
        "What does the <figure> tag define?": "Self-contained content, often with a caption",
        "What tag is used to add a caption to a <figure>?": "<figcaption>",
        "Which tag groups introductory content or navigational links?": "<header>",
        "Which element is used to group related options in a drop-down list?": "<optgroup>",
        "What tag is used to define an option in a drop-down list?": "<option>",
        "Which tag is used to create a drop-down list?": "<select>",
        "Which attribute in <input> specifies the type of input control?": "type",
        "What does the <label> tag do?": "Defines a label for an <input> element",
        "What does the <form> element define?": "An HTML form for user input",
        "Which tag is used to group form elements?": "<fieldset>",
        "What tag defines a title for a <fieldset>?": "<legend>",
        "Which tag is used to embed an iframe?": "<iframe>",
        "What tag is used to define metadata about an HTML document?": "<meta>",
        "What tag defines a script in an HTML document?": "<script>",
        "Which tag is used to link external JavaScript files?": "<script src='...'>",
        "What tag is used to define a style section?": "<style>",
        "What attribute in <a> specifies the URL?": "href",
        "What attribute in <img> specifies the image source?": "src",
        "What does the <canvas> element do?": "Draw graphics via scripting (e.g., JavaScript)",
        "What is the purpose of the <noscript> tag?": "Defines fallback content for users without JavaScript",
        "Which HTML5 tag is used for marking up a time/date?": "<time>",
        "Which tag represents user input in a document?": "<kbd>",
        "What tag is used for inline code snippets?": "<code>",
        "What tag is used to define preformatted text?": "<pre>",
        "Which tag is used to define a progress bar?": "<progress>",
        "What does the <datalist> tag do?": "Specifies a list of pre-defined options for <input>",
        "What tag is used to define a dialog box or window?": "<dialog>",
    },

    # CSS
    "CSS": {
        "How do you change the background color in CSS?": "background-color",
        "What is the default position value in CSS?": "static",
        "Which unit is relative to the root element's font size?": "rem",
        "What property is used to make text bold?": "font-weight",
        "How do you select an element by class?": ".classname",
        "How do you select an element by ID?": "#idname",
        "What property is used to change text color?": "color",
        "Which property sets the size of text?": "font-size",
        "What property adds space inside an element's border?": "padding",
        "What property adds space outside an element's border?": "margin",
        "Which property is used to make text italic?": "font-style",
        "How do you center text horizontally?": "text-align: center",
        "Which property changes the type of cursor shown?": "cursor",
        "What CSS property controls the stacking order of elements?": "z-index",
        "Which property makes an element float to the right or left?": "float",
        "What is the use of 'clear' in CSS?": "It specifies what elements can float beside the cleared element",
        "What property is used to apply a shadow to text?": "text-shadow",
        "What property changes the font family?": "font-family",
        "Which CSS property is used to set the height of an element?": "height",
        "Which CSS property sets the width of an element?": "width",
        "What property is used to hide an element?": "display: none",
        "What value of 'display' turns an element into a block-level element?": "display: block",
        "What value of 'display' makes an element inline?": "display: inline",
        "What value of 'display' is used for flexbox layouts?": "display: flex",
        "What property enables grid layout?": "display: grid",
        "How do you create space between grid items?": "gap",
        "What CSS property specifies the stacking order of elements?": "z-index",
        "Which property controls how content overflows its box?": "overflow",
        "What value of 'position' places an element relative to its closest positioned ancestor?": "absolute",
        "What value of 'position' keeps an element fixed during scroll?": "fixed",
        "What value of 'position' allows sticky behavior during scrolling?": "sticky",
        "What CSS function is used to apply gradients?": "linear-gradient",
        "What property is used to set a background image?": "background-image",
        "How do you make a border rounded?": "border-radius",
        "Which property adds a shadow to a box?": "box-shadow",
        "How do you transform an element (e.g., rotate or scale)?": "transform",
        "What property is used to animate changes?": "transition",
        "How do you set multiple background images?": "background-image: url(...), url(...)",
        "Which shorthand sets margin in all directions?": "margin: top right bottom left",
        "What value makes an element fully transparent?": "opacity: 0",
        "How do you make an element partially transparent?": "Use 'opacity' between 0 and 1",
        "What property sets the alignment of items in flexbox?": "align-items",
        "Which property justifies items in flex container?": "justify-content",
        "What unit scales with the parent’s font size?": "em",
        "What does the 'inherit' value do?": "Takes the property value from the parent element",
        "What pseudo-class targets the first child?": ":first-child",
        "What pseudo-class targets elements on hover?": ":hover",
        "How do you select all elements of a certain type?": "elementname",
        "What symbol combines selectors in a group?": ",",
        "How do you apply styles only to direct children?": ">",
        "What pseudo-class targets an element when it is focused?": ":focus",
    },

    # Django
    "Django": {
        "Which file contains URL patterns in a Django app?": "urls.py",
        "What command creates a new Django project?": "django-admin startproject",
        "What does ORM stand for in Django?": "Object-Relational Mapping",
        "Which file defines the models in a Django app?": "models.py",
        "What is the name of Django’s template language?": "Django Template Language (DTL)",
        "Which file handles static files like CSS and JavaScript in a Django app?": "static/",
        "What is the purpose of the 'migrations' folder in Django?": "To store database schema changes",
        "How do you apply migrations in Django?": "python manage.py migrate",
        "What is a view in Django?": "A function or class that receives web requests and returns web responses",
        "What is the default database used by Django?": "SQLite",
        "Which command starts the development server in Django?": "python manage.py runserver",
        "What is the purpose of Django's admin interface?": "To manage the data of the application through a web interface",
        "How do you create a superuser in Django?": "python manage.py createsuperuser",
        "What does the 'urlpatterns' list in 'urls.py' define?": "The URL routing for the Django app",
        "What is the purpose of the 'settings.py' file in Django?": "It contains the configuration and settings for the Django project",
        "Which method is used to get the value of a query parameter in Django views?": "request.GET.get()",
        "How do you set a session variable in Django?": "request.session['key'] = value",
        "What is a Django model?": "A Python class that defines the structure of database tables",
        "What is Django REST Framework used for?": "To build RESTful APIs in Django",
        "Which method is used to define a serializer class in Django REST Framework?": "serializers.ModelSerializer",
        "What is the default permission class in Django REST Framework?": "IsAuthenticated",
        "Which method in Django REST Framework is used to create a viewset?": "viewsets.ModelViewSet",
        "What is the function of 'APIView' in Django REST Framework?": "It provides basic handling of HTTP methods in an API view",
        "How do you handle authentication in Django REST Framework?": "By using authentication classes like 'BasicAuthentication' or 'TokenAuthentication'",
        "What is a Django Form?": "A class that handles form data validation and rendering",
        "What is the function of the 'csrf_token' template tag?": "To protect forms against Cross-Site Request Forgery (CSRF) attacks",
        "What is a Django middleware?": "A class that processes requests before and after a view is called",
        "Which decorator is used to mark a Django view as requiring login?": "@login_required",
        "What is a ForeignKey in Django models?": "A field that creates a one-to-many relationship between models",
        "How do you create a one-to-one relationship in Django models?": "Using OneToOneField",
        "Which class is used to define a view that handles GET and POST requests in Django?": "FormView",
        "What method is used to create database tables from Django models?": "python manage.py makemigrations",
        "How do you include a static file in a Django template?": "{% static 'path/to/file' %}",
        "What is the purpose of the 'context' dictionary in Django views?": "It holds the data passed to the template",
        "What is a Django signal?": "A mechanism to allow decoupled applications to get notified when certain actions occur",
        "How do you make a Django model field unique?": "By setting unique=True in the model field definition",
        "What is Django’s default password hasher?": "PBKDF2",
        "How do you create a custom management command in Django?": "By creating a management/commands directory in a Django app",
        "What is the purpose of 'django.contrib.auth' module?": "It provides authentication and authorization support",
        "How do you define many-to-many relationships in Django models?": "Using ManyToManyField",
        "What is the 'django.db.models.Manager' class used for?": "It defines methods for querying a model",
        "How do you create a custom query in Django?": "By writing custom manager methods",
        "What is the purpose of the 'gettext' function in Django?": "For marking strings for translation in Django applications",
        "What are Django’s generic class-based views?": "Pre-built views for common patterns like list views and detail views",
        "How do you prevent a Django model from being saved to the database?": "By using the 'save()' method with the 'force_insert=False' argument",
        "What is the 'django.core.exceptions.ValidationError' used for?": "To raise an error during form or model validation",
        "What is a Django query set?": "A collection of database queries that can be filtered, ordered, and modified",
        "How do you update a record in a Django model?": "By modifying an instance and calling save()",
        "How do you create an API endpoint in Django REST Framework?": "By defining a viewset and registering it with a router",
        "What does the 'serializer' do in Django REST Framework?": "It converts model instances into JSON format and validates input data",
        "What is the function of 'pagination' in Django REST Framework?": "To limit the number of records returned in a response",
        "How do you enable CORS (Cross-Origin Resource Sharing) in Django?": "By installing and configuring 'django-cors-headers'",
        "How do you set up a default API version in Django REST Framework?": "By defining a versioning class in the settings.py file",
        "What is the purpose of Django’s 'signals' framework?": "To allow decoupled applications to be notified of certain actions in the application",
        "What is the function of 'django.contrib.sessions' middleware?": "To manage user sessions for persisting data across requests",
        "How do you add custom validation to Django model fields?": "By overriding the 'clean()' method in the model",
    },

    # FastAPI
    "FastAPI": {
        "Which Python decorator is used to define a GET endpoint in FastAPI?": "@app.get",
        "What library does FastAPI use for data validation?": "Pydantic",
        "Which command runs a FastAPI app with auto-reload?": "uvicorn app:app --reload",
        "What is the default response format in FastAPI?": "JSON",
        "Which FastAPI feature automatically generates interactive API docs?": "Swagger UI",
        "Which method is used to create a POST endpoint in FastAPI?": "@app.post",
        "How do you handle query parameters in FastAPI?": "Using function arguments",
        "How do you define a path parameter in FastAPI?": "By using curly braces in the path, e.g., /items/{item_id}",
        "Which class is used to define a request body in FastAPI?": "Pydantic models",
        "How do you add validation to query parameters in FastAPI?": "By using Pydantic models or type hints",
        "How do you handle HTTP exceptions in FastAPI?": "By raising HTTPException with a status code and detail",
        "What method is used to define a PUT endpoint in FastAPI?": "@app.put",
        "How do you handle form data in FastAPI?": "Using the 'Form' helper",
        "How do you include a file upload in a FastAPI request?": "Using the 'File' helper",
        "How do you enable CORS in FastAPI?": "By using 'CORSMiddleware' from 'fastapi.middleware.cors'",
        "What is the default status code returned by FastAPI if not specified?": "200 OK",
        "How do you add authentication in FastAPI?": "By using OAuth2, JWT, or API keys",
        "Which method in FastAPI is used for retrieving data by a specific query string?": "@app.get",
        "How do you add custom headers in FastAPI responses?": "By using the 'Response' object and setting custom headers",
        "What is the function of the 'Depends' dependency in FastAPI?": "To inject dependencies into endpoint functions",
        "How do you validate query parameters in FastAPI?": "By using Pydantic models or directly as function arguments with type hints",
        "Which FastAPI function is used to return JSON responses?": "JSONResponse",
        "What library is used by FastAPI for request and response body parsing?": "Starlette",
        "How do you add a description to a FastAPI endpoint?": "By using the 'description' parameter in the decorator",
        "How do you make an endpoint secure with OAuth2 in FastAPI?": "By using OAuth2PasswordBearer and OAuth2PasswordRequestForm",
        "How do you handle background tasks in FastAPI?": "By using 'BackgroundTasks' in the endpoint function",
        "Which command is used to install FastAPI and Uvicorn?": "pip install fastapi uvicorn",
        "How do you enable automatic validation in FastAPI?": "By using Pydantic models with type hints",
        "What does FastAPI use for request/response handling?": "Starlette framework",
        "Which method would you use to define a DELETE endpoint in FastAPI?": "@app.delete",
        "How do you pass headers to an endpoint in FastAPI?": "By using the 'Header' dependency",
        "What does the 'Path' dependency in FastAPI do?": "It allows you to define path parameters with validation",
        "How do you specify response models in FastAPI?": "By using the 'response_model' parameter in the route decorator",
        "What does the 'status_code' parameter in FastAPI decorator do?": "It sets the HTTP status code for a response",
        "How do you handle large file uploads in FastAPI?": "By using the 'File' helper and specifying 'UploadFile' as the type",
        "What is the purpose of the 'Request' object in FastAPI?": "To access the raw HTTP request data",
        "How do you perform dependency injection for a function in FastAPI?": "By using the 'Depends' helper in the function signature",
        "How do you handle exceptions globally in FastAPI?": "By using exception handlers with the 'app.exception_handler' decorator",
        "How do you enable HTTPS for a FastAPI application?": "By setting up Uvicorn with an SSL certificate",
        "Which library is used by FastAPI to generate interactive documentation for APIs?": "Swagger UI (via OpenAPI)",
        "What is the function of 'APIRouter' in FastAPI?": "It is used to create modular and reusable routes",
        "How do you log requests and responses in FastAPI?": "By using middleware or custom logging functions",
        "How do you define a default value for a query parameter in FastAPI?": "By setting a default value in the function argument",
        "What does 'Body' dependency in FastAPI help with?": "It is used to extract data from the request body",
        "How do you create a FastAPI application instance?": "By calling FastAPI()",
        "How do you add pagination to a FastAPI response?": "By manually calculating offsets and limits or using query parameters",
        "How do you handle cookies in FastAPI?": "By using the 'Cookie' dependency",
        "What is the function of 'JSONResponse' in FastAPI?": "It is used to send a JSON response with a custom status code",
        "How do you specify a list of allowed methods in a FastAPI endpoint?": "By using the 'methods' parameter in the decorator",
        "How do you define a FastAPI app to support asynchronous operations?": "By defining endpoint functions as 'async def'",
        "Which function is used to get the request's JSON body in FastAPI?": "await request.json()",
        "How do you add validation to path parameters in FastAPI?": "By using Pydantic models or type hints directly in the path",
        "How do you document query parameters in FastAPI?": "By using function argument descriptions or Pydantic models",
        "What does the 'Include' functionality in FastAPI's documentation do?": "It includes the content of specified routes in the documentation",
    }
}
